version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: spincity-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: spincity_db
    ports:
      - "3307:3306"

  backend:
    build: .
    container_name: spincity-backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/spincity_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 60000

  frontend:
    build: ../frontend   # 👈 adjust path if needed
    container_name: spincity-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
